# Copyright 2025 Canonical
# See LICENSE file for licensing details.

import logging

import jubilant
from requests import Session

from . import APPNAME, HAPROXY, SSC, DNSResolverHTTPSAdapter, retry, wait_oneshot_finished


def deploy_ha_wait_func(status):
    """Wait on juju status until deployed and started."""
    app_maintenance = status.apps[APPNAME].is_maintenance
    started = status.apps[APPNAME].app_status.message == "Starting transition"
    haproxy_active = status.apps[HAPROXY].is_active
    ssc_active = status.apps[SSC].is_active
    logging.debug(f"app_maintenance: {app_maintenance}")
    logging.debug(f"started: {started}")
    logging.debug(f"haproxy_active: {haproxy_active}")
    logging.debug(f"ssc_active: {ssc_active}")
    return app_maintenance and started and haproxy_active and ssc_active


def test_deploy(juju: jubilant.Juju, transition_tracker_charm):
    """Deploy the charm along haproxy and wait until it fully completed."""
    juju.deploy(transition_tracker_charm, app=APPNAME)
    juju.deploy(
        HAPROXY, channel="2.8/edge", config={"external-hostname": "transition-tracker.internal"}
    )
    juju.deploy(SSC, channel="1/edge")

    juju.integrate(APPNAME, HAPROXY)
    juju.integrate(f"{HAPROXY}:certificates", f"{SSC}:certificates")

    juju.wait(deploy_ha_wait_func, timeout=1800)
    wait_oneshot_finished(
        juju, unit="transition-tracker/0", service="ubuntu-transition-tracker.service"
    )


@retry(retry_num=24, retry_sleep_sec=5)
def test_ingress_functions_correctly(juju: jubilant.Juju):
    """Check if the response through haproxy matches the expected content."""
    model_name = juju.model
    assert model_name is not None

    haproxy_ip = juju.status().apps[HAPROXY].units[f"{HAPROXY}/0"].public_address
    external_hostname = "transition-tracker.internal"

    session = Session()
    session.mount("https://", DNSResolverHTTPSAdapter(external_hostname, haproxy_ip))
    response = session.get(
        f"https://{haproxy_ip}/{model_name}-{APPNAME}/",
        headers={"Host": external_hostname},
        verify=False,
        timeout=30,
    )

    assert response.status_code == 200
    # This is real content, which is dynamic - check header and footer
    expected_header = (
        '<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">'
        '<head><title>Transition tracker</title><meta charset="utf-8"/>'
        '<link rel="stylesheet" href="media/revamp.css"/>'
        '<link rel="stylesheet" href="media/styles.css"/></head>'
        '<body class="debian"><h1 id="title">Ubuntu Release Management</h1>'
        '<h2 id="subtitle">Transition tracker</h2><div id="body">'
    )
    assert response.text.startswith(expected_header)
    assert '<div id="footer"><small>Page generated by' in response.text
