# Copyright 2025 Canonical
# See LICENSE file for licensing details.

import logging

import jubilant
import requests

from . import APPNAME, retry, wait_oneshot_finished


def deploy_wait_func(status):
    """Wait on juju status until deployed and started."""
    all_maint = jubilant.all_maintenance(status)
    started = status.apps[APPNAME].app_status.message == "Starting transition"
    ready = all_maint and started
    logging.debug(f"all_maint: {all_maint}")
    logging.debug(f"started: {started}")
    return ready


def address(juju: jubilant.Juju):
    """Report the IP address of the application."""
    return juju.status().apps[APPNAME].units[f"{APPNAME}/0"].public_address


def test_deploy(juju: jubilant.Juju, transition_tracker_charm):
    """Deploy the charm via jubilant and wait until it fully completed."""
    juju.deploy(transition_tracker_charm, app=APPNAME)
    juju.wait(deploy_wait_func, timeout=600)
    wait_oneshot_finished(
        juju, unit="transition-tracker/0", service="ubuntu-transition-tracker.service"
    )


@retry(retry_num=10, retry_sleep_sec=3)
def test_content(juju: jubilant.Juju):
    """Check if the response matches the expected transition page content."""
    response = requests.get(f"http://{address(juju)}:80", timeout=15)
    assert response.status_code == 200
    # This is real content, which is dynamic - check header and footer
    expected_header = (
        '<!DOCTYPE html>\n<html xmlns="http://www.w3.org/1999/xhtml">'
        '<head><title>Transition tracker</title><meta charset="utf-8"/>'
        '<link rel="stylesheet" href="media/revamp.css"/>'
        '<link rel="stylesheet" href="media/styles.css"/></head>'
        '<body class="debian"><h1 id="title">Ubuntu Release Management</h1>'
        '<h2 id="subtitle">Transition tracker</h2><div id="body">'
    )
    assert response.text.startswith(expected_header)
    assert '<div id="footer"><small>Page generated by' in response.text
